package:
  name: openocd
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_rev: master
  git_url: git://repo.or.cz/openocd.git
  patches:
    - digilent-arty.patch
    - digilent-arty-s7.patch
    - digilent-cmod-a7.patch
    - digilent-nexys_video.patch
    - gadgetfactory-papilio_duo.patch
    - numato-neso.patch
    - numato-saturn.patch
    - numato-waxwing.patch
    - fpga-program.patch
    - spartan7-idcodes.patch

build:
  # y==GIT_DESCRIBE_NUMBER, z==DATE_NUM, x==GIT_DESCRIBE_HASH
  #
  # number: 10693001803050325
  #         1yyyy00zzzzzzzzzz
  number: {{ '1%04i00%s'|format(GIT_DESCRIBE_NUMBER|int, os.environ.get('DATE_NUM')) }}
  # string: 0693.20180305_0325.g588ce0e3
  #         yyyy.zzzzzzzz_zzzz.gxxxxxxxx
  string: {{ '%04i'|format(GIT_DESCRIBE_NUMBER|int) }}.{{ os.environ.get('DATE_STR') }}.{{ GIT_DESCRIBE_HASH }}
  script_env:
    - CI
    - TRAVIS

test:
  commands:
    - openocd -v
    - if ldd $(which openocd) | grep ftdi; then echo "libftdi found :-("; exit 1; fi
    - if ldd $(which openocd) | grep usb; then echo "libusb found :-("; exit 1; fi

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
