package:
  name: gcc-lm32-elf-newlib
  version: 5.4.0

source:
  fn: gcc-5.4.0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
  sha256: 608df76dec2d34de6558249d8af4cbee21eceddbcb580d666f7a5a583ca3303a
  patches:
   - stdint.patch
   - reload1.patch

extra:
  sources:
    newlib:
      fn: newlib-2.5.0.20170228.tar.gz
      url: ftp://sourceware.org/pub/newlib/newlib-2.5.0.20170228.tar.gz
      sha256: 29923e9696b091dc2f880018e747c8cf282a557d2cdb60f760d9ec6a1f97337d

build:
  detect_binary_files_with_prefix: False
  number: 1
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - gcc_linux-64
    - gxx_linux-64
    - libgcc-ng
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-lm32-elf
    - gcc-lm32-elf-nostdc
  run:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-lm32-elf
    - gcc-lm32-elf-nostdc

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
