package:
  name: vtr
  version: {{ GIT_DESCRIBE_TAG|replace('vpr-','') }}

source:
  git_url: https://github.com/SymbiFlow/vtr-verilog-to-routing.git
  git_rev: symbiflow

build:
  # y==GIT_DESCRIBE_NUMBER, z==DATE_NUM, x==GIT_DESCRIBE_HASH
  #
  # number: 10693001803050325
  #         1yyyy00zzzzzzzzzz
  number: {{ '1%04i00%s'|format(GIT_DESCRIBE_NUMBER|int, os.environ.get('DATE_NUM')) }}
  # string: 0693.20180305_0325.g588ce0e3
  #         yyyy.zzzzzzzz_zzzz.gxxxxxxxx
  string: {{ '%04i'|format(GIT_DESCRIBE_NUMBER|int) }}.{{ os.environ.get('DATE_STR') }}.{{ GIT_DESCRIBE_HASH }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bison
    - cairo
    - cmake
    - flex
    - fontconfig
    - ncurses
    - pkg-config
    - readline
    - tk
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxcb
    - xorg-libxext
    - xorg-libxft
  run:
    - readline
    - tk
    - cairo
    - fontconfig
    - xorg-libx11
    - xorg-libxft

#test:
#  commands:
#    - ./run_reg_test.pl vtr_reg_basic
#    - ./run_reg_test.pl vtr_reg_strong -j2

about:
  home: http://verilogtorouting.org/
  license: MIT
  license_file: LICENSE.md
  summary: 'The Verilog-to-Routing (VTR) project is a world-wide collaborative effort to provide a open-source framework for conducting FPGA architecture and CAD research and development. The VTR design flow takes as input a Verilog description of a digital circuit, and a description of the target FPGA architecture.'
