language: c

#dist: trusty
sudo: false
addons:
  apt:
    update: true
    packages:
    - realpath
    - autoconf
    - automake
    - build-essential
    - gperf
    - libftdi-dev
    - libudev-dev
    - libudev1
    - libusb-1.0-0-dev
    - libusb-dev
    - texinfo

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

env:
  # lm32 toolchain
  - PACKAGE=binutils            TOOLCHAIN_ARCH=lm32
  - PACKAGE=gcc/nostdc          TOOLCHAIN_ARCH=lm32
  - PACKAGE=gcc/newlib          TOOLCHAIN_ARCH=lm32
  - PACKAGE=gdb                 TOOLCHAIN_ARCH=lm32
  # or1k toolchain
  - PACKAGE=binutils            TOOLCHAIN_ARCH=or1k
  - PACKAGE=gcc/nostdc          TOOLCHAIN_ARCH=or1k
  - PACKAGE=gcc/newlib          TOOLCHAIN_ARCH=or1k
  - PACKAGE=gdb                 TOOLCHAIN_ARCH=or1k
  # riscv32 toolchain
  - PACKAGE=binutils            TOOLCHAIN_ARCH=riscv32
  # sh2 toolchain
  - PACKAGE=binutils            TOOLCHAIN_ARCH=sh2
  # fx2 toolchain
  - PACKAGE=sdcc
  # tools
  - PACKAGE=openocd
  - PACKAGE=flterm
  # verilog tools
  - PACKAGE=arachne-pnr
  - PACKAGE=icestorm
  - PACKAGE=iverilog
  - PACKAGE=nextpnr
  - PACKAGE=verilator
  - PACKAGE=vtr                 CONDA_CHANNELS=conda-forge
  - PACKAGE=yosys

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
  - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh
