language: c

#dist: trusty
sudo: false
addons:
  apt:
    update: true
    packages:
    - realpath
    - autoconf
    - automake
    - build-essential
    - gperf
    - libftdi-dev
    - libudev-dev
    - libudev1
    - libusb-1.0-0-dev
    - libusb-dev
    - texinfo

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh


jobs:
  include:
   # lm32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32

   # or1k toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32

   # sh2 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh2

   # Verilog tools
   - stage: "Verilog Tools"
     env:
     - PACKAGE=arachne-pnr

   - stage: "Verilog Tools"
     env:
     - PACKAGE=icestorm

   - stage: "Verilog Tools"
     env:
     - PACKAGE=iverilog

   - stage: "Verilog Tools"
     env:
     - PACKAGE=nextpnr

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilator

#   - stage: "Verilog Tools"
#     env:
#     - PACKAGE=vtr                 CONDA_CHANNELS=conda-forge

   - stage: "Verilog Tools"
     env:
     - PACKAGE=yosys

   - stage: "Other Tools"
     env:
     - PACKAGE=sdcc

   - stage: "Other Tools"
     env:
     - PACKAGE=iceprog

   - stage: "Other Tools"
     env:
     - PACKAGE=openocd

   - stage: "Other Tools"
     env:
     - PACKAGE=flterm

matrix:
  allow_failures:
  - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
  - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh
