language: minimal

dist: xenial
addons:
  apt:
    update: true
    packages:
    - realpath
    - autoconf
    - automake
    - build-essential
    - gperf
    - libftdi-dev
    - libudev-dev
    - libudev1
    - libusb-1.0-0-dev
    - libusb-dev
    - texinfo

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh


jobs:
  include:
   # Libraries
   - stage: "Libraries"
     env:
     - PACKAGE=lib/isl

   - stage: "Libraries"
     env:
     - PACKAGE=lib/usb

   - stage: "Libraries"
     env:
     - PACKAGE=lib/ftdi

   # or1k toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=or1k
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=or1k
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=or1k

   # rv32 toolchain
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=riscv32
   - stage: "GCC - Linux (musl)"
     env:
     - PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=riscv32

   # lm32 toolchain - no linux
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=lm32
   - stage: "GCC - nostdc"
     env:
     - PACKAGE=gcc/nostdc   TOOLCHAIN_ARCH=lm32
   - stage: "GCC - newlib"
     env:
     - PACKAGE=gcc/newlib   TOOLCHAIN_ARCH=lm32
   - stage: "GDB"
     env:
     - PACKAGE=gdb          TOOLCHAIN_ARCH=lm32

   # sh2 toolchain - no gcc?
   - stage: "Binutils"
     env:
     - PACKAGE=binutils     TOOLCHAIN_ARCH=sh2

   # Full Linux musl toolchain using musl-cross-make
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=or1k
   - stage: "Toolchain - Linux MUSL"
     env:
     - PACKAGE=toolchain/linux-musl TOOLCHAIN_ARCH=riscv32

   # Other tools
   - stage: "Other Tools"
     env:
     - PACKAGE=sdcc

   # Programming Tools

   - stage: "Programming Tools"
     env:
     - PACKAGE=prog/iceprog

   - stage: "Other Tools"
     env:
     - PACKAGE=prog/icefunprog

   - stage: "Other Tools"
     env:
     - PACKAGE=prog/openocd

   - stage: "Other Tools"
     env:
     - PACKAGE=prog/flterm

   - stage: "Other Tools"
     env:
     - PACKAGE=prog/fxload

   - stage: "Other Tools"
     env:
     - PACKAGE=prog/dfu-util

   # Verilog tools
   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/arachne-pnr

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/icestorm

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/prjtrellis

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/icarus

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/iverilog

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/nextpnr/ice40

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/nextpnr/ecp5

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/nextpnr/generic

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/verilator

#   - stage: "Verilog Tools"
#     env:
#     - PACKAGE=verilog/vtr                 CONDA_CHANNELS=conda-forge

   - stage: "Verilog Tools"
     env:
     - PACKAGE=verilog/yosys

matrix:
  allow_failures:
  - env: PACKAGE=vtr CONDA_CHANNELS=conda-forge
  fast_finish: true

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
  - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh
