{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: ghdlsynth
  version: {{ version }}

source:
 - git_url: https://https://github.com/ghdl/ghdl.git
   git_rev: master
   folder: ghdl
 - git_url: https://github.com/tgingold/ghdlsynth-beta.git
   git_rev: master
   folder: ghdlsynth-beta


build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 3.7
    - fontconfig
  host:
    - bison
    - boost
    - eigen
    - flex
    - pkg-config
    - python 3.7
    - yosys
  run:
    - python
    - yosys

test:
  commands:
    - nextpnr-ice40 -V

about:
  home: https://github.com/YosysHQ/nextpnr
  license: ISC
  license_file: COPYING
  summary: 'nextpnr aims to be a vendor neutral, timing driven, FOSS FPGA place and route tool.'
