{% set ns = namespace(surelog_version='0.0', yosys_version='0.0') %}
{% for package in resolved_packages('host') %}
  {% if package.startswith( 'surelog-uhdm ' ) %}
    {% set ns.surelog_version = package.split()[1] %}
  {% endif %}
  {% if package.startswith( 'yosys-uhdm ' ) %}
    {% set ns.yosys_version = package.split()[1] %}
  {% endif %}
{% endfor %}

{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}
{% set build_string = '%s_%s'|format(DATE_STR, py_suffix) %}

package:
  name: uhdm-integration-yosys
  version: {{ ns.yosys_version }}

build:
  string: {{ build_string }}

requirements:
  host:
    - surelog-uhdm=*={{ build_string }}
    - yosys-uhdm=*={{ build_string }}
  run:
    - surelog-uhdm={{ ns.surelog_version }}={{ build_string }}
    - yosys-uhdm={{ ns.yosys_version }}={{ build_string }}
