package:
  name: arachne-pnr
  version: {{ GIT_DESCRIBE_TAG|replace('arachne-pnr-','') }}

source:
  git_url: https://github.com/mithro/arachne-pnr.git
  git_rev: master

build:
  # y==GIT_DESCRIBE_NUMBER, z==DATE_NUM, x==GIT_DESCRIBE_HASH
  #
  # number: 10693001803050325
  #         1yyyy00zzzzzzzzzz
  number: {{ '1%04i00%s'|format(GIT_DESCRIBE_NUMBER|int, os.environ.get('DATE_NUM')) }}
  # string: 0693.20180305_0325.g588ce0e3
  #         yyyy.zzzzzzzz_zzzz.gxxxxxxxx
  string: {{ '%04i'|format(GIT_DESCRIBE_NUMBER|int) }}.{{ os.environ.get('DATE_STR') }}.{{ GIT_DESCRIBE_HASH }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison
    - flex
    - icestorm
    - iverilog
    - libffi
    - libgcc-ng
    - pkg-config
    - readline
    - tk
    - yosys
  run:
    - icestorm
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

about:
  home: http://www.clifford.at/arachne-pnr/
  license_file: COPYING
  summary: 'Arachne-pnr implements the place and route step of the hardware compilation process for FPGAs. It accepts as input a technology-mapped netlist in BLIF format, as output by the Yosys [0] synthesis suite for example. It currently targets the Lattice Semiconductor iCE40 family of FPGAs. Its output is a textual bitstream representation for assembly by the IceStorm icepack command. The output of icepack is a binary bitstream which can be uploaded to a hardware device. Together, Yosys, arachne-pnr and IceStorm provide an fully open-source Verilog-to-bistream tool chain for iCE40 1K and 8K FPGA development. Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'

extra:
  maintainers:
    - Tim 'mithro' Ansell <mithro@mithis.com>
    - HDMI2USB Project - https://hdmi2usb.tv <hdmi2usb@googlegroups.com>
