{% set ns = namespace(version='0.0') %}
{% for package in resolved_packages('host') %}
  {% if package.startswith( 'vtr-gui ' ) %}
    {% set ns.version = package.split()[1] %}
  {% endif %}
{% endfor %}

package:
  name: quicklogic-vtr-gui
  version: {{ ns.version }}
build:
  string: {{ DATE_STR }}
requirements:
  host:
    - vtr-gui=*={{ DATE_STR }}
  run:
    - vtr-gui={{ ns.version }}={{ DATE_STR }}
about:
  home: http://verilogtorouting.org/
  license: MIT
  summary: 'A metapackage installing upstream version of the Verilog-to-Routing (VTR) with GUI support.'
