# Use `conda-build-prepare` before building for a better version string.
package:
  name: antmicro-yosys-plugins
  version: 0.0

source:
  git_url: https://github.com/antmicro/ibex-yosys-build.git
  git_rev: master

build:
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - iverilog
    - antmicro-yosys
  run:
    - antmicro-yosys

