package:
  name: symbiflow-yosys-plugins
  version: 0.0

source:
  git_url: https://github.com/SymbiFlow/yosys-symbiflow-plugins.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - pkg-config
    - readline
    - bison
    - tk
    - libffi
    - flex
    - iverilog
    - symbiflow-yosys
  run:
    - symbiflow-yosys

