{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: prjxray-db
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/prjxray-db.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

about:
  home: https://github.com/SymbiFlow/prjxray-db
  license: CC0-1.0
  license_file: LICENSE
  summary: 'Project X-Ray Database: XC7 Series.'
