name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    #    branches: [ master ]
  pull_request:
  workflow_dispatch:
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 69
defaults:
  run:
    shell: bash
jobs:
  #68
  yosys-uhdm-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master
