name: build-packages
on: [push, pull_request]
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 68
defaults:
  run:
    shell: bash
jobs:
  #6
  icarus-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ./.github/action
