name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 71
defaults:
  run:
    shell: bash
jobs:
  #61
  antmicro-yosys-complete-linux:
    runs-on: "ubuntu-16.04"
    needs: "antmicro-yosys-plugins-linux"
    env:
      PACKAGE: "sim/antmicro-yosys-complete"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #62
  antmicro-yosys-plugins-linux:
    runs-on: "ubuntu-16.04"
    needs: ["antmicro-yosys-linux"]
    env:
      PACKAGE: "syn/antmicro-yosys-plugins"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #63
  antmicro-yosys-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/antmicro-yosys"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master
