package:
  name: flterm
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/timvideos/flterm.git

build:
  # y==GIT_DESCRIBE_NUMBER, z==DATESTR, x==GIT_DESCRIBE_HASH
  #
  # number: 10693001803050325
  #         1yyyy00zzzzzzzzzz
  number: {{ '1%04i00%s'|format(environ.get('GIT_DESCRIBE_NUMBER')|int, environ.get('DATESTR')) }}
  # string: 0693.1803050325.g588ce0e3
  #         yyyy.zzzzzzzzzz.gxxxxxxxx
  string: {{ '%04i'|format(environ.get('GIT_DESCRIBE_NUMBER')|int) }}.{{ environ.get('DATESTR') }}.{{ environ.get('GIT_DESCRIBE_HASH', 'unknown') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  commands:
    - flterm --help

about:
  home: https://github.com/timvideos/flterm
  license: GPLv3
  summary: 'Serial boot program for MiSoC'
